hydra:
  run:
    dir: ${log_root_path}
  job:
    chdir: false

defaults:
  - _self_

# checkpoint: checkpoints/check-resnet/default_resnet_0618050306/770000_000009.pt
name: p2m_with_template
log_root_path: logs/${hydra:job.name}/${name}/${now:%Y-%m-%dT%H:%M:%S}
dataset_root_path: datasets/data/shapenet_with_template

checkpoint_path: null
dataset:
  camera_c:
    - 111.5
    - 111.5
  camera_f:
    - 248.0
    - 248.0
  mesh_pos:
    - 0.0
    - 0.0
    - -0.8
  name: shapenet_with_template
  normalization: true
  num_classes: 13
  predict:
    folder: /tmp
  shapenet:
    num_points: 9000
    resize_with_constant_border: false
  subset_eval: test_tf
  subset_train: train_tf
  # subset_eval: test_tf_small
  # subset_train: train_tf_small
loss:
  weights:
    chamfer:
      - 1.0
      - 1.0
      - 1.0
    chamfer_opposite: 0.55
    constant: 1.0
    edge: 0.1
    laplace: 0.5
    move: 0.033
    normal: 0.00016
    reconst: 0.0
model:
  align_with_tensorflow: false
  backbone: resnet50
  coord_dim: 3
  gconv_activation: true
  hidden_dim: 192
  last_hidden_dim: 192
  name: pixel2mesh_with_template
  z_threshold: 0
num_gpus: 1
num_workers: 16
optim:
  adam_beta1: 0.9
  # lr: 0.0001
  lr: 0.001
  lr_factor: 0.3
  lr_step:
    - 30
    - 70
    - 90
  name: adam
  sgd_momentum: 0.9
  wd: 1.0e-06
# batch_size: 32
batch_size: 4
num_epochs: 200
test:
  weighted_mean: false

mtl_filepath: "rendering.mtl"
usemtl_name: "Default_OBJ.001"
random_seed: 0
